module.exports = {
  uri: 'https://delivery.mindfulcms.com/im/default/compat/native-email/email-placement',
  placements: {
    'cen-today': {
      'toc-1': '675084ac7d99348589e9a171',
      'toc-2': '675084b77d99348589e9a173',
      'inline-1': '675084bb3fb3246ab45b8545',
      'inline-2': '675084e23fb3246ab45b8547',
    },
    'design-development-today': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'design-development-weekly-comp': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'design-development-weekly-tim-podcast': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'design-development-weekly': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'engineering-news-today': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'fm-today': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'fm-weeky-tim-podcast': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'fm-weekly': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'food-video-showcase': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'id-ma-monthly': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'id-today': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'id-video-showcase': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'ien-digi-key-integrator': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'ien-today': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'ien-update': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'ien-weekly-tim-podcast': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'ien-weekly': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'impo-insider': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'impo-video-showcase': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'industrial-management-today': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'manufacturing-today': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'manufacturing-today-comp': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'mbt-today': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'mdd-video-showcase': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'ot-security-update-weekly': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'today-medical-design-development': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
    'video-showcase': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
    },
  },
};
