module.exports = {
  uri: 'https://delivery.mindfulcms.com/im/default/compat/native-email/email-placement',
  placements: {
    'cen-today': {
      'toc-1': '675084ac7d99348589e9a171',
      'toc-2': '675084b77d99348589e9a173',
      'inline-1': '675084bb3fb3246ab45b8545',
      'inline-2': '675084e23fb3246ab45b8547',
      'inline-3': '6759efecf18e33525669b715',
      'inline-4': '6759efeff18e33525669b717',
      'inline-5': '6759eff2f18e33525669b719',
    },
    'design-development-today': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'design-development-weekly-comp': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'design-development-weekly-tim-podcast': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'design-development-weekly': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'engineering-news-today': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'fm-today': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'fm-weeky-tim-podcast': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'fm-weekly': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'food-video-showcase': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'id-ma-monthly': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'id-today': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'id-video-showcase': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'ien-digi-key-integrator': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'ien-today': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'ien-update': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'ien-weekly-tim-podcast': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'ien-weekly': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'impo-insider': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'impo-video-showcase': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'industrial-management-today': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'manufacturing-today': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'manufacturing-today-comp': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'mbt-today': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'mdd-video-showcase': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'ot-security-update-weekly': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'today-medical-design-development': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'video-showcase': {
      'toc-1': '',
      'toc-2': '',
      'inline-1': '',
      'inline-2': '',
      'inline-3': '',
      'inline-4': '',
      'inline-5': '',
    },
    'industrial-software-technology': {
      'toc-1': '6759ef67f18e33525669b70b',
      'toc-2': '6759ef6bf18e33525669b70d',
      'inline-1': '6759ef7094030f0c221c7e82',
      'inline-2': '6759ef72f18e33525669b70f',
      'inline-3': '6759ef75584bddb2d6cdfa91',
      'inline-4': '6759ef77f18e33525669b711',
      'inline-5': '6759f12f584bddb2d6cdfa93',
    },
  },
};
